version: '3'

services:
  es_schwantes:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es_schwantes
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana_schwantes:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana_schwantes
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - SERVER_NAME=127.0.0.1
      - ELASTICSEARCH_HOSTS=http://es_schwantes:9200
    depends_on:
      - es_schwantes
    ports:
      - 5601:5601
    networks:
      - elastic

volumes:
  elastic_data:

networks:
  elastic:
    driver: bridge
